# Generated by Django 2.2.4 on 2024-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240119_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='favorite_books',
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
